# Generated by Django 4.1.5 on 2023-02-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarsection',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
