# Generated by Django 4.1.5 on 2023-02-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_section', '0003_grammartopic_type_of_topic_grammartheorysection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammartopic',
            name='type_of_topic',
        ),
    ]
