# Generated by Django 4.1.5 on 2023-02-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_section', '0004_remove_grammartopic_type_of_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartheorysection',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
