# Generated by Django 4.1.3 on 2023-01-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_cases', '0002_rename_url_case_slug_rename_url_topic_slug_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='initial_form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='translation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
