# Generated by Django 4.1.3 on 2023-01-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_cases', '0003_exercise_initial_form_exercise_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
