# Generated by Django 4.1.3 on 2023-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_cases', '0004_alter_exercise_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='second_part',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
