# Generated by Django 4.1.3 on 2022-11-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_newuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
